name: MightyRTP
version: 1.0.4
main: com.example.mightyrtp.MightyRTP
api-version: '1.17'
authors: [MightyFinger77]
description: A powerful random teleporter plugin for Minecraft servers with BetterRTP compatibility, console command support, and world-specific teleportation

commands:
  rtp:
    description: Teleport to a random safe location (supports BetterRTP format, console execution, and world specification)
    usage: /rtp [player] [world] or /rtp player <player> [world]
    permission: mightyrtp.rtp
    permission-message: You don't have permission to use this command!
  rtp-reload:
    description: Reload the plugin configuration
    usage: /rtp-reload
    permission: mightyrtp.reload
    permission-message: You don't have permission to use this command!

permissions:
  mightyrtp.rtp:
    description: Allows players to use RTP command
    default: true
  mightyrtp.rtp.other:
    description: Allows players to use RTP command on other players
    default: op
  mightyrtp.rtp.world:
    description: Allows players to use RTP command with world specification
    default: op
  mightyrtp.bypass:
    description: Allows players to bypass the cooldown limit
    default: op
  mightyrtp.reload:
    description: Allows players to reload the plugin configuration
    default: op
